#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
TOTAL_STAGES=6

# All values for this site live in .env.local, not .env.
ENV_FILE=".env.local"

banner "Google reviews setup — iProtectCare"

# ── Stage 1: Google Business Profile ──────────────────────────────────────
stage "Google Business Profile"
say "The reviews section shows reviews from your Google Business Profile."
say "Without a verified profile there is nothing to fetch."
open_url "https://business.google.com"
step "Sign in with the shop's Google account (iprotectcaretechnology@gmail.com)."
step "Add 'iProtectCare' with the Koramangala address if it isn't listed yet."
step "Complete verification (Google may post a card / call — can take days)."
note "Already have a verified profile? Just continue."
warn "Reviews only appear on the website once real customers leave them."
pause

# ── Stage 2: Place ID ─────────────────────────────────────────────────────
stage "Find your Place ID"
say "The Place ID tells the API exactly which business to read."
open_url "https://developers.google.com/maps/documentation/places/web-service/place-id"
step "Scroll to the interactive 'Place ID Finder' map on that page."
step "Search: iProtectCare Koramangala Bengaluru"
step "Click the shop's pin — the Place ID appears (starts with 'ChIJ...')."
note "Shop not on the map yet? Its profile isn't live — finish Stage 1 first."
ask GOOGLE_PLACE_ID "Paste the Place ID:"

# ── Stage 3: Enable the Places API (New) ──────────────────────────────────
stage "Enable Places API (New)"
say "The API lives in Google Cloud — one free project is enough."
open_url "https://console.cloud.google.com/apis/library/places.googleapis.com"
step "Sign in with the same Google account."
step "If asked, create a project (name it e.g. 'iprotectcare-website')."
step "Press the blue 'Enable' button for 'Places API (New)'."
note "Billing prompt? Google requires a billing account, but one place lookup"
note "per day sits far inside the free monthly credit — cost stays ₹0."
pause "Enabled? Press Enter."

# ── Stage 4: Create the API key ───────────────────────────────────────────
stage "Create an API key"
open_url "https://console.cloud.google.com/apis/credentials"
step "Click '+ Create credentials' → 'API key', then copy the key."
step "Recommended: click the new key → under 'API restrictions' choose"
step "'Restrict key' → tick only 'Places API (New)' → Save."
ask_secret GOOGLE_PLACES_API_KEY "Paste the API key (input hidden):"

# ── Stage 5: Save locally and verify live ─────────────────────────────────
stage "Save and verify"
write_env GOOGLE_PLACE_ID "$GOOGLE_PLACE_ID"
write_env GOOGLE_PLACES_API_KEY "$GOOGLE_PLACES_API_KEY"
say "Calling the live API with your new key..."
_resp=$(curl -s -w '\n%{http_code}' \
  -H "X-Goog-Api-Key: ${GOOGLE_PLACES_API_KEY}" \
  "https://places.googleapis.com/v1/places/${GOOGLE_PLACE_ID}?fields=displayName,rating,userRatingCount" || true)
_code=${_resp##*$'\n'}
_body=${_resp%$'\n'*}
if [[ "$_code" == "200" ]]; then
  printf '  %s✓ API works.%s Google says: %s\n' "$GREEN" "$RESET" \
    "$(printf '%s' "$_body" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(f"{d.get(\"displayName\",{}).get(\"text\",\"?\")} — rating {d.get(\"rating\",\"none yet\")}, {d.get(\"userRatingCount\",0)} review(s)")' 2>/dev/null || echo "$_body")"
  note "0 reviews is fine — the section stays hidden until reviews exist."
else
  warn "API call failed (HTTP $_code)."
  note "$_body"
  note "Usual causes: API not enabled yet (Stage 3), key restricted to the"
  note "wrong API (Stage 4), or a typo in the Place ID (Stage 2)."
  SKIPPED+=("Verify the API call works, then restart the dev server")
fi
note "Restart 'npm run dev' to see it locally (once reviews exist)."
pause

# ── Stage 6: Vercel (production) ──────────────────────────────────────────
stage "Add the vars to Vercel"
say "Production reads env vars from the Vercel dashboard, not .env.local."
open_url "https://vercel.com/dashboard"
step "Open the iprotectcare-website project → Settings → Environment Variables."
step "Add GOOGLE_PLACE_ID with the value you pasted in Stage 2."
step "Add GOOGLE_PLACES_API_KEY with the key from Stage 4 (all environments)."
step "Redeploy (Deployments → ⋯ on the latest → Redeploy) to pick them up."
if ! confirm "Both variables added to Vercel?"; then
  SKIPPED+=("Add GOOGLE_PLACE_ID + GOOGLE_PLACES_API_KEY in Vercel, then redeploy")
fi

finish
