import type { Device } from "./types";

export const iphone: Device = {
  slug: "iphone-repair",
  name: "iPhone",
  navLabel: "iPhone Repair",
  heroTitle: "iPhone repair in Koramangala",
  heroSub:
    "Cracked screens, worn batteries, charging faults and more — diagnosed free, quoted upfront, and often fixed the same day.",
  formDeviceType: "iPhone",
  image: { src: "/images/devices/iphone.jpg", alt: "Three iPhones seen from the back and side" },
  models: [
    "iPhone 8",
    "iPhone 8 Plus",
    "iPhone X",
    "iPhone XR",
    "iPhone XS",
    "iPhone XS Max",
    "iPhone 11",
    "iPhone 11 Pro",
    "iPhone 11 Pro Max",
    "iPhone SE (2nd gen, 2020)",
    "iPhone 12 mini",
    "iPhone 12",
    "iPhone 12 Pro",
    "iPhone 12 Pro Max",
    "iPhone 13 mini",
    "iPhone 13",
    "iPhone 13 Pro",
    "iPhone 13 Pro Max",
    "iPhone SE (3rd gen, 2022)",
    "iPhone 14",
    "iPhone 14 Plus",
    "iPhone 14 Pro",
    "iPhone 14 Pro Max",
    "iPhone 15",
    "iPhone 15 Plus",
    "iPhone 15 Pro",
    "iPhone 15 Pro Max",
    "iPhone 16",
    "iPhone 16 Plus",
    "iPhone 16 Pro",
    "iPhone 16 Pro Max",
    "iPhone 16e",
    "iPhone 17",
    "iPhone 17 Pro",
    "iPhone 17 Pro Max",
    "iPhone Air",
  ],
  repairs: [
    {
      slug: "screen",
      name: "Screen replacement",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Cracked, flickering or unresponsive displays replaced with quality-tested panels.",
    },
    {
      slug: "battery",
      name: "Battery replacement",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Restore full-day battery life and stop unexpected shutdowns.",
    },
    {
      slug: "charging-port",
      name: "Charging port repair",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Loose cables, slow charging or no charging at all.",
    },
    {
      slug: "back-glass",
      name: "Back glass replacement",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Shattered rear glass replaced cleanly, keeping wireless charging working.",
    },
    {
      slug: "camera",
      name: "Camera repair",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Blurry photos, shaking lenses, black screens — front or rear.",
    },
    {
      slug: "water-damage",
      name: "Water damage treatment",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Ultrasonic cleaning and board-level treatment after liquid exposure.",
    },
    {
      slug: "data-recovery",
      name: "Data recovery",
      priceBand: "Quoted at your free diagnosis",
      blurb: "Photos and files recovered from iPhones that no longer switch on.",
    },
  ],
  faq: [
    {
      q: "My iPhone screen is cracked but the display works. Should I still replace it?",
      a: "A cracked screen usually spreads and can eventually damage the display or cut your finger. Replacing the glass early is cheaper than replacing a failed display later.",
    },
    {
      q: "Will I lose my data during an iPhone repair?",
      a: "No — screen, battery and port repairs don't touch your data. We still recommend having a backup, as with any hardware work.",
    },
    {
      q: "How long does an iPhone screen replacement take?",
      a: "For popular models we usually have it done the same day, often within a couple of hours if the part is in stock.",
    },
    {
      q: "My iPhone got wet and won't turn on. What should I do?",
      a: "Don't charge it — that's what causes most of the damage. Switch it off if you can and bring it in as soon as possible for ultrasonic cleaning.",
    },
  ],
  metaTitle: "iPhone Repair in Koramangala, Bengaluru | iProtectCare",
  metaDescription:
    "iPhone screen, battery, charging port and water damage repair in Koramangala, Bengaluru. Free diagnosis, fixed quotes, warranty on every repair, same-day on common fixes.",
};
